version: '3.8'

services:
  # PostgreSQL database for production-like testing
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: adkdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MoEngage Support Agent Server
  support-agent:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=local
      # Database Configuration - Option 1: Full connection string
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/adkdb
      # Database Configuration - Option 2: Individual components (alternative)
      # - DB_HOST=postgres
      # - DB_PORT=5432
      # - DB_NAME=adkdb
      # - DB_USER=postgres
      # - DB_PASSWORD=postgres
      - MCP_LOCAL_ENDPOINT=http://host.docker.internal:8001
      - MCP_SSE_URL=http://host.docker.internal:8080/sse
      - MCP_SSE_TIMEOUT=200
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=http://localhost,http://localhost:8080,http://localhost:3000
      # LLM Model Configuration
      - LLM_MODEL_DEFAULT=gemini-2.5-flash-preview-05-20
      - LLM_MODEL_TECHNICAL=gemini-2.5-flash-preview-05-20
      - LLM_MODEL_PUSH=gemini-2.5-flash-preview-05-20
      - LLM_MODEL_WHATSAPP=gemini-2.5-flash-preview-05-20
      - LLM_MODEL_KNOWLEDGE=gemini-2.5-flash-preview-05-20
      - LLM_MODEL_FOLLOWUP=gemini-2.5-flash-preview-05-20
      - LLM_MODEL_TICKET=gemini-2.5-flash-preview-05-20
      - LLM_MODEL_EXECUTION=gemini-2.5-flash-preview-05-20
      - LLM_MODEL_ROOT=gemini-2.5-flash-preview-05-20
      # Add your Google service account credentials here
      - GOOGLE_PROJECT_ID=agent-ai-initiatives
      - GOOGLE_PRIVATE_KEY_ID=your_private_key_id
      - GOOGLE_PRIVATE_KEY=your_private_key
      - GOOGLE_CLIENT_EMAIL=discovery-engine-aws-app@agent-ai-initiatives.iam.gserviceaccount.com
      - GOOGLE_CLIENT_ID=your_client_id
      - GOOGLE_CLIENT_X509_CERT_URL=your_cert_url
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./local_data:/app/local_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: 